export default {
  location: {
    name: 'Istanbul',
    region: 'Istanbul',
    country: 'Turkey',
    lat: 41.02,
    lon: 28.96,
    tz_id: 'Europe/Istanbul',
    localtime_epoch: 1679138935,
    localtime: '2023-03-18 14:28',
  },
  current: {
    last_updated_epoch: 1679138100,
    last_updated: '2023-03-18 14:15',
    temp_c: 8.0,
    temp_f: 46.4,
    is_day: 1,
    condition: {
      text: 'Light rain',
      icon: '//cdn.weatherapi.com/weather/64x64/day/296.png',
      code: 1183,
    },
    wind_mph: 15.0,
    wind_kph: 24.1,
    wind_degree: 360,
    wind_dir: 'N',
    pressure_mb: 1019.0,
    pressure_in: 30.09,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 81,
    cloud: 75,
    feelslike_c: 4.7,
    feelslike_f: 40.4,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 2.0,
    gust_mph: 16.1,
    gust_kph: 25.9,
  },
  forecast: {
    forecastday: [
      {
        date: '2023-03-18',
        date_epoch: 1679097600,
        day: {
          maxtemp_c: 7.5,
          maxtemp_f: 45.5,
          mintemp_c: 6.8,
          mintemp_f: 44.2,
          avgtemp_c: 7.1,
          avgtemp_f: 44.8,
          maxwind_mph: 13.6,
          maxwind_kph: 22.0,
          totalprecip_mm: 6.0,
          totalprecip_in: 0.24,
          totalsnow_cm: 0.0,
          avgvis_km: 8.5,
          avgvis_miles: 5.0,
          avghumidity: 85.0,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 85,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Moderate rain',
            icon: '//cdn.weatherapi.com/weather/64x64/day/302.png',
            code: 1189,
          },
          uv: 2.0,
        },
        astro: {
          sunrise: '07:12 AM',
          sunset: '07:14 PM',
          moonrise: '05:37 AM',
          moonset: '03:08 PM',
          moon_phase: 'Waning Crescent',
          moon_illumination: '19',
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1679086800,
            time: '2023-03-18 00:00',
            temp_c: 7.0,
            temp_f: 44.6,
            is_day: 0,
            condition: {
              text: 'Light rain shower',
              icon: '//cdn.weatherapi.com/weather/64x64/night/353.png',
              code: 1240,
            },
            wind_mph: 13.2,
            wind_kph: 21.2,
            wind_degree: 9,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 85,
            cloud: 100,
            feelslike_c: 3.5,
            feelslike_f: 38.3,
            windchill_c: 3.5,
            windchill_f: 38.3,
            heatindex_c: 7.0,
            heatindex_f: 44.6,
            dewpoint_c: 4.6,
            dewpoint_f: 40.3,
            will_it_rain: 1,
            chance_of_rain: 75,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.6,
            gust_kph: 29.9,
            uv: 1.0,
          },
          {
            time_epoch: 1679090400,
            time: '2023-03-18 01:00',
            temp_c: 7.1,
            temp_f: 44.8,
            is_day: 0,
            condition: {
              text: 'Light rain shower',
              icon: '//cdn.weatherapi.com/weather/64x64/night/353.png',
              code: 1240,
            },
            wind_mph: 13.0,
            wind_kph: 20.9,
            wind_degree: 9,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 85,
            cloud: 100,
            feelslike_c: 3.6,
            feelslike_f: 38.5,
            windchill_c: 3.6,
            windchill_f: 38.5,
            heatindex_c: 7.1,
            heatindex_f: 44.8,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 0,
            chance_of_rain: 67,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.7,
            gust_kph: 28.4,
            uv: 1.0,
          },
          {
            time_epoch: 1679094000,
            time: '2023-03-18 02:00',
            temp_c: 7.0,
            temp_f: 44.6,
            is_day: 0,
            condition: {
              text: 'Light rain',
              icon: '//cdn.weatherapi.com/weather/64x64/night/296.png',
              code: 1183,
            },
            wind_mph: 12.5,
            wind_kph: 20.2,
            wind_degree: 8,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 1.6,
            precip_in: 0.06,
            humidity: 85,
            cloud: 100,
            feelslike_c: 3.6,
            feelslike_f: 38.5,
            windchill_c: 3.6,
            windchill_f: 38.5,
            heatindex_c: 7.0,
            heatindex_f: 44.6,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 1,
            chance_of_rain: 77,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 17.2,
            gust_kph: 27.7,
            uv: 1.0,
          },
          {
            time_epoch: 1679097600,
            time: '2023-03-18 03:00',
            temp_c: 7.0,
            temp_f: 44.6,
            is_day: 0,
            condition: {
              text: 'Light drizzle',
              icon: '//cdn.weatherapi.com/weather/64x64/night/266.png',
              code: 1153,
            },
            wind_mph: 12.5,
            wind_kph: 20.2,
            wind_degree: 8,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.08,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 86,
            cloud: 100,
            feelslike_c: 3.6,
            feelslike_f: 38.5,
            windchill_c: 3.6,
            windchill_f: 38.5,
            heatindex_c: 7.0,
            heatindex_f: 44.6,
            dewpoint_c: 4.9,
            dewpoint_f: 40.8,
            will_it_rain: 1,
            chance_of_rain: 85,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 16.8,
            gust_kph: 27.0,
            uv: 1.0,
          },
          {
            time_epoch: 1679101200,
            time: '2023-03-18 04:00',
            temp_c: 7.0,
            temp_f: 44.6,
            is_day: 0,
            condition: {
              text: 'Light drizzle',
              icon: '//cdn.weatherapi.com/weather/64x64/night/266.png',
              code: 1153,
            },
            wind_mph: 13.0,
            wind_kph: 20.9,
            wind_degree: 8,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.08,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 87,
            cloud: 100,
            feelslike_c: 3.5,
            feelslike_f: 38.3,
            windchill_c: 3.5,
            windchill_f: 38.3,
            heatindex_c: 7.0,
            heatindex_f: 44.6,
            dewpoint_c: 5.0,
            dewpoint_f: 41.0,
            will_it_rain: 1,
            chance_of_rain: 79,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 17.0,
            gust_kph: 27.4,
            uv: 1.0,
          },
          {
            time_epoch: 1679104800,
            time: '2023-03-18 05:00',
            temp_c: 6.8,
            temp_f: 44.2,
            is_day: 0,
            condition: {
              text: 'Light rain',
              icon: '//cdn.weatherapi.com/weather/64x64/night/296.png',
              code: 1183,
            },
            wind_mph: 13.2,
            wind_kph: 21.2,
            wind_degree: 11,
            wind_dir: 'NNE',
            pressure_mb: 1018.0,
            pressure_in: 30.07,
            precip_mm: 0.8,
            precip_in: 0.03,
            humidity: 87,
            cloud: 100,
            feelslike_c: 3.2,
            feelslike_f: 37.8,
            windchill_c: 3.2,
            windchill_f: 37.8,
            heatindex_c: 6.8,
            heatindex_f: 44.2,
            dewpoint_c: 4.8,
            dewpoint_f: 40.6,
            will_it_rain: 1,
            chance_of_rain: 78,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 17.9,
            gust_kph: 28.8,
            uv: 1.0,
          },
          {
            time_epoch: 1679108400,
            time: '2023-03-18 06:00',
            temp_c: 6.8,
            temp_f: 44.2,
            is_day: 0,
            condition: {
              text: 'Light drizzle',
              icon: '//cdn.weatherapi.com/weather/64x64/night/266.png',
              code: 1153,
            },
            wind_mph: 13.0,
            wind_kph: 20.9,
            wind_degree: 11,
            wind_dir: 'NNE',
            pressure_mb: 1018.0,
            pressure_in: 30.07,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 86,
            cloud: 100,
            feelslike_c: 3.2,
            feelslike_f: 37.8,
            windchill_c: 3.2,
            windchill_f: 37.8,
            heatindex_c: 6.8,
            heatindex_f: 44.2,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 1,
            chance_of_rain: 85,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 17.2,
            gust_kph: 27.7,
            uv: 1.0,
          },
          {
            time_epoch: 1679112000,
            time: '2023-03-18 07:00',
            temp_c: 6.8,
            temp_f: 44.2,
            is_day: 0,
            condition: {
              text: 'Light rain shower',
              icon: '//cdn.weatherapi.com/weather/64x64/night/353.png',
              code: 1240,
            },
            wind_mph: 12.1,
            wind_kph: 19.4,
            wind_degree: 9,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.08,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 86,
            cloud: 100,
            feelslike_c: 3.4,
            feelslike_f: 38.1,
            windchill_c: 3.4,
            windchill_f: 38.1,
            heatindex_c: 6.8,
            heatindex_f: 44.2,
            dewpoint_c: 4.6,
            dewpoint_f: 40.3,
            will_it_rain: 1,
            chance_of_rain: 77,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 1.0,
          },
          {
            time_epoch: 1679115600,
            time: '2023-03-18 08:00',
            temp_c: 7.1,
            temp_f: 44.8,
            is_day: 1,
            condition: {
              text: 'Light rain',
              icon: '//cdn.weatherapi.com/weather/64x64/day/296.png',
              code: 1183,
            },
            wind_mph: 11.2,
            wind_kph: 18.0,
            wind_degree: 9,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 1.0,
            precip_in: 0.04,
            humidity: 85,
            cloud: 100,
            feelslike_c: 4.0,
            feelslike_f: 39.2,
            windchill_c: 4.0,
            windchill_f: 39.2,
            heatindex_c: 7.1,
            heatindex_f: 44.8,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 0,
            chance_of_rain: 66,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 14.3,
            gust_kph: 23.0,
            uv: 2.0,
          },
          {
            time_epoch: 1679119200,
            time: '2023-03-18 09:00',
            temp_c: 7.2,
            temp_f: 45.0,
            is_day: 1,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 11.0,
            wind_kph: 17.6,
            wind_degree: 6,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 85,
            cloud: 100,
            feelslike_c: 4.1,
            feelslike_f: 39.4,
            windchill_c: 4.1,
            windchill_f: 39.4,
            heatindex_c: 7.2,
            heatindex_f: 45.0,
            dewpoint_c: 4.8,
            dewpoint_f: 40.6,
            will_it_rain: 0,
            chance_of_rain: 60,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.1,
            gust_kph: 22.7,
            uv: 2.0,
          },
          {
            time_epoch: 1679122800,
            time: '2023-03-18 10:00',
            temp_c: 7.3,
            temp_f: 45.1,
            is_day: 1,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 2,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 85,
            cloud: 100,
            feelslike_c: 4.2,
            feelslike_f: 39.6,
            windchill_c: 4.2,
            windchill_f: 39.6,
            heatindex_c: 7.3,
            heatindex_f: 45.1,
            dewpoint_c: 5.0,
            dewpoint_f: 41.0,
            will_it_rain: 1,
            chance_of_rain: 72,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.3,
            gust_kph: 23.0,
            uv: 2.0,
          },
          {
            time_epoch: 1679126400,
            time: '2023-03-18 11:00',
            temp_c: 7.5,
            temp_f: 45.5,
            is_day: 1,
            condition: {
              text: 'Light drizzle',
              icon: '//cdn.weatherapi.com/weather/64x64/day/266.png',
              code: 1153,
            },
            wind_mph: 12.1,
            wind_kph: 19.4,
            wind_degree: 359,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 86,
            cloud: 100,
            feelslike_c: 4.3,
            feelslike_f: 39.7,
            windchill_c: 4.3,
            windchill_f: 39.7,
            heatindex_c: 7.5,
            heatindex_f: 45.5,
            dewpoint_c: 5.2,
            dewpoint_f: 41.4,
            will_it_rain: 1,
            chance_of_rain: 82,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 14.8,
            gust_kph: 23.8,
            uv: 2.0,
          },
          {
            time_epoch: 1679130000,
            time: '2023-03-18 12:00',
            temp_c: 7.5,
            temp_f: 45.5,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 12.8,
            wind_kph: 20.5,
            wind_degree: 359,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 100,
            feelslike_c: 4.2,
            feelslike_f: 39.6,
            windchill_c: 4.2,
            windchill_f: 39.6,
            heatindex_c: 7.5,
            heatindex_f: 45.5,
            dewpoint_c: 5.2,
            dewpoint_f: 41.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.4,
            gust_kph: 24.8,
            uv: 2.0,
          },
          {
            time_epoch: 1679133600,
            time: '2023-03-18 13:00',
            temp_c: 7.4,
            temp_f: 45.3,
            is_day: 1,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 13.2,
            wind_kph: 21.2,
            wind_degree: 358,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 84,
            cloud: 100,
            feelslike_c: 4.0,
            feelslike_f: 39.2,
            windchill_c: 4.0,
            windchill_f: 39.2,
            heatindex_c: 7.4,
            heatindex_f: 45.3,
            dewpoint_c: 5.0,
            dewpoint_f: 41.0,
            will_it_rain: 0,
            chance_of_rain: 69,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 2.0,
          },
          {
            time_epoch: 1679137200,
            time: '2023-03-18 14:00',
            temp_c: 7.4,
            temp_f: 45.3,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 13.6,
            wind_kph: 22.0,
            wind_degree: 357,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 100,
            feelslike_c: 3.9,
            feelslike_f: 39.0,
            windchill_c: 3.9,
            windchill_f: 39.0,
            heatindex_c: 7.4,
            heatindex_f: 45.3,
            dewpoint_c: 5.0,
            dewpoint_f: 41.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.1,
            gust_kph: 25.9,
            uv: 2.0,
          },
          {
            time_epoch: 1679140800,
            time: '2023-03-18 15:00',
            temp_c: 7.3,
            temp_f: 45.1,
            is_day: 1,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 13.4,
            wind_kph: 21.6,
            wind_degree: 357,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 85,
            cloud: 100,
            feelslike_c: 3.8,
            feelslike_f: 38.8,
            windchill_c: 3.8,
            windchill_f: 38.8,
            heatindex_c: 7.3,
            heatindex_f: 45.1,
            dewpoint_c: 4.9,
            dewpoint_f: 40.8,
            will_it_rain: 1,
            chance_of_rain: 72,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 2.0,
          },
          {
            time_epoch: 1679144400,
            time: '2023-03-18 16:00',
            temp_c: 7.3,
            temp_f: 45.1,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 13.4,
            wind_kph: 21.6,
            wind_degree: 356,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 100,
            feelslike_c: 3.8,
            feelslike_f: 38.8,
            windchill_c: 3.8,
            windchill_f: 38.8,
            heatindex_c: 7.3,
            heatindex_f: 45.1,
            dewpoint_c: 4.9,
            dewpoint_f: 40.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.7,
            gust_kph: 25.2,
            uv: 2.0,
          },
          {
            time_epoch: 1679148000,
            time: '2023-03-18 17:00',
            temp_c: 7.0,
            temp_f: 44.6,
            is_day: 1,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 12.5,
            wind_kph: 20.2,
            wind_degree: 356,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 85,
            cloud: 100,
            feelslike_c: 3.6,
            feelslike_f: 38.5,
            windchill_c: 3.6,
            windchill_f: 38.5,
            heatindex_c: 7.0,
            heatindex_f: 44.6,
            dewpoint_c: 4.6,
            dewpoint_f: 40.3,
            will_it_rain: 1,
            chance_of_rain: 83,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.2,
            gust_kph: 24.5,
            uv: 2.0,
          },
          {
            time_epoch: 1679151600,
            time: '2023-03-18 18:00',
            temp_c: 6.9,
            temp_f: 44.4,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 355,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 100,
            feelslike_c: 3.8,
            feelslike_f: 38.8,
            windchill_c: 3.8,
            windchill_f: 38.8,
            heatindex_c: 6.9,
            heatindex_f: 44.4,
            dewpoint_c: 4.5,
            dewpoint_f: 40.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.2,
            gust_kph: 21.2,
            uv: 2.0,
          },
          {
            time_epoch: 1679155200,
            time: '2023-03-18 19:00',
            temp_c: 7.1,
            temp_f: 44.8,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 356,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 100,
            feelslike_c: 4.4,
            feelslike_f: 39.9,
            windchill_c: 4.4,
            windchill_f: 39.9,
            heatindex_c: 7.1,
            heatindex_f: 44.8,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.4,
            gust_kph: 18.4,
            uv: 2.0,
          },
          {
            time_epoch: 1679158800,
            time: '2023-03-18 20:00',
            temp_c: 6.9,
            temp_f: 44.4,
            is_day: 0,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009,
            },
            wind_mph: 8.1,
            wind_kph: 13.0,
            wind_degree: 357,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 100,
            feelslike_c: 4.4,
            feelslike_f: 39.9,
            windchill_c: 4.4,
            windchill_f: 39.9,
            heatindex_c: 6.9,
            heatindex_f: 44.4,
            dewpoint_c: 4.6,
            dewpoint_f: 40.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.7,
            gust_kph: 17.3,
            uv: 1.0,
          },
          {
            time_epoch: 1679162400,
            time: '2023-03-18 21:00',
            temp_c: 7.2,
            temp_f: 45.0,
            is_day: 0,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 352,
            wind_dir: 'N',
            pressure_mb: 1020.0,
            pressure_in: 30.11,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 86,
            cloud: 100,
            feelslike_c: 4.9,
            feelslike_f: 40.8,
            windchill_c: 4.9,
            windchill_f: 40.8,
            heatindex_c: 7.2,
            heatindex_f: 45.0,
            dewpoint_c: 5.1,
            dewpoint_f: 41.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 1.0,
          },
          {
            time_epoch: 1679166000,
            time: '2023-03-18 22:00',
            temp_c: 7.1,
            temp_f: 44.8,
            is_day: 0,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 348,
            wind_dir: 'NNW',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 87,
            cloud: 100,
            feelslike_c: 4.8,
            feelslike_f: 40.6,
            windchill_c: 4.8,
            windchill_f: 40.6,
            heatindex_c: 7.1,
            heatindex_f: 44.8,
            dewpoint_c: 5.1,
            dewpoint_f: 41.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.1,
            gust_kph: 16.2,
            uv: 1.0,
          },
          {
            time_epoch: 1679169600,
            time: '2023-03-18 23:00',
            temp_c: 7.1,
            temp_f: 44.8,
            is_day: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 346,
            wind_dir: 'NNW',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 87,
            cloud: 100,
            feelslike_c: 4.8,
            feelslike_f: 40.6,
            windchill_c: 4.8,
            windchill_f: 40.6,
            heatindex_c: 7.1,
            heatindex_f: 44.8,
            dewpoint_c: 5.1,
            dewpoint_f: 41.2,
            will_it_rain: 1,
            chance_of_rain: 76,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 1.0,
          },
        ],
      },
      {
        date: '2023-03-19',
        date_epoch: 1679184000,
        day: {
          maxtemp_c: 10.0,
          maxtemp_f: 50.0,
          mintemp_c: 6.7,
          mintemp_f: 44.1,
          avgtemp_c: 8.6,
          avgtemp_f: 47.4,
          maxwind_mph: 9.6,
          maxwind_kph: 15.5,
          totalprecip_mm: 0.2,
          totalprecip_in: 0.01,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 85.0,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 85,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Patchy rain possible',
            icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
            code: 1063,
          },
          uv: 2.0,
        },
        astro: {
          sunrise: '07:10 AM',
          sunset: '07:15 PM',
          moonrise: '06:14 AM',
          moonset: '04:28 PM',
          moon_phase: 'Waning Crescent',
          moon_illumination: '10',
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1679173200,
            time: '2023-03-19 00:00',
            temp_c: 6.8,
            temp_f: 44.2,
            is_day: 0,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 329,
            wind_dir: 'NNW',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 88,
            cloud: 96,
            feelslike_c: 4.4,
            feelslike_f: 39.9,
            windchill_c: 4.4,
            windchill_f: 39.9,
            heatindex_c: 6.8,
            heatindex_f: 44.2,
            dewpoint_c: 4.9,
            dewpoint_f: 40.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.5,
            gust_kph: 16.9,
            uv: 1.0,
          },
          {
            time_epoch: 1679176800,
            time: '2023-03-19 01:00',
            temp_c: 6.7,
            temp_f: 44.1,
            is_day: 0,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 327,
            wind_dir: 'NNW',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 88,
            cloud: 92,
            feelslike_c: 4.5,
            feelslike_f: 40.1,
            windchill_c: 4.5,
            windchill_f: 40.1,
            heatindex_c: 6.7,
            heatindex_f: 44.1,
            dewpoint_c: 4.8,
            dewpoint_f: 40.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 1.0,
          },
          {
            time_epoch: 1679180400,
            time: '2023-03-19 02:00',
            temp_c: 6.7,
            temp_f: 44.1,
            is_day: 0,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 315,
            wind_dir: 'NW',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 87,
            cloud: 87,
            feelslike_c: 5.4,
            feelslike_f: 41.7,
            windchill_c: 5.4,
            windchill_f: 41.7,
            heatindex_c: 6.7,
            heatindex_f: 44.1,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 1.0,
          },
          {
            time_epoch: 1679184000,
            time: '2023-03-19 03:00',
            temp_c: 6.9,
            temp_f: 44.4,
            is_day: 0,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 283,
            wind_dir: 'WNW',
            pressure_mb: 1019.0,
            pressure_in: 30.08,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 86,
            cloud: 92,
            feelslike_c: 6.5,
            feelslike_f: 43.7,
            windchill_c: 6.5,
            windchill_f: 43.7,
            heatindex_c: 6.9,
            heatindex_f: 44.4,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 1.0,
          },
          {
            time_epoch: 1679187600,
            time: '2023-03-19 04:00',
            temp_c: 7.1,
            temp_f: 44.8,
            is_day: 0,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 268,
            wind_dir: 'W',
            pressure_mb: 1019.0,
            pressure_in: 30.08,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 92,
            feelslike_c: 6.7,
            feelslike_f: 44.1,
            windchill_c: 6.7,
            windchill_f: 44.1,
            heatindex_c: 7.1,
            heatindex_f: 44.8,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 1.0,
          },
          {
            time_epoch: 1679191200,
            time: '2023-03-19 05:00',
            temp_c: 7.2,
            temp_f: 45.0,
            is_day: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 2.0,
            wind_kph: 3.2,
            wind_degree: 267,
            wind_dir: 'W',
            pressure_mb: 1019.0,
            pressure_in: 30.08,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 85,
            cloud: 88,
            feelslike_c: 7.3,
            feelslike_f: 45.1,
            windchill_c: 7.3,
            windchill_f: 45.1,
            heatindex_c: 7.2,
            heatindex_f: 45.0,
            dewpoint_c: 4.8,
            dewpoint_f: 40.6,
            will_it_rain: 1,
            chance_of_rain: 72,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.7,
            gust_kph: 4.3,
            uv: 1.0,
          },
          {
            time_epoch: 1679194800,
            time: '2023-03-19 06:00',
            temp_c: 7.2,
            temp_f: 45.0,
            is_day: 0,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006,
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 263,
            wind_dir: 'W',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 84,
            cloud: 75,
            feelslike_c: 7.2,
            feelslike_f: 45.0,
            windchill_c: 7.2,
            windchill_f: 45.0,
            heatindex_c: 7.2,
            heatindex_f: 45.0,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 1.6,
            gust_kph: 2.5,
            uv: 1.0,
          },
          {
            time_epoch: 1679198400,
            time: '2023-03-19 07:00',
            temp_c: 7.5,
            temp_f: 45.5,
            is_day: 0,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 2,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 83,
            cloud: 78,
            feelslike_c: 7.5,
            feelslike_f: 45.5,
            windchill_c: 7.5,
            windchill_f: 45.5,
            heatindex_c: 7.5,
            heatindex_f: 45.5,
            dewpoint_c: 4.8,
            dewpoint_f: 40.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 1.8,
            gust_kph: 2.9,
            uv: 1.0,
          },
          {
            time_epoch: 1679202000,
            time: '2023-03-19 08:00',
            temp_c: 8.0,
            temp_f: 46.4,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 44,
            wind_dir: 'NE',
            pressure_mb: 1020.0,
            pressure_in: 30.11,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 79,
            cloud: 93,
            feelslike_c: 8.0,
            feelslike_f: 46.4,
            windchill_c: 8.0,
            windchill_f: 46.4,
            heatindex_c: 8.0,
            heatindex_f: 46.4,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.2,
            gust_kph: 3.6,
            uv: 2.0,
          },
          {
            time_epoch: 1679205600,
            time: '2023-03-19 09:00',
            temp_c: 8.6,
            temp_f: 47.5,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 2.0,
            wind_kph: 3.2,
            wind_degree: 18,
            wind_dir: 'NNE',
            pressure_mb: 1020.0,
            pressure_in: 30.12,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 76,
            cloud: 100,
            feelslike_c: 8.9,
            feelslike_f: 48.0,
            windchill_c: 8.9,
            windchill_f: 48.0,
            heatindex_c: 8.6,
            heatindex_f: 47.5,
            dewpoint_c: 4.6,
            dewpoint_f: 40.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.5,
            gust_kph: 4.0,
            uv: 2.0,
          },
          {
            time_epoch: 1679209200,
            time: '2023-03-19 10:00',
            temp_c: 9.0,
            temp_f: 48.2,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 9,
            wind_dir: 'N',
            pressure_mb: 1020.0,
            pressure_in: 30.12,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 75,
            cloud: 100,
            feelslike_c: 8.1,
            feelslike_f: 46.6,
            windchill_c: 8.1,
            windchill_f: 46.6,
            heatindex_c: 9.0,
            heatindex_f: 48.2,
            dewpoint_c: 4.8,
            dewpoint_f: 40.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 2.0,
          },
          {
            time_epoch: 1679212800,
            time: '2023-03-19 11:00',
            temp_c: 9.8,
            temp_f: 49.6,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 10,
            wind_dir: 'N',
            pressure_mb: 1020.0,
            pressure_in: 30.12,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 76,
            cloud: 100,
            feelslike_c: 8.3,
            feelslike_f: 46.9,
            windchill_c: 8.3,
            windchill_f: 46.9,
            heatindex_c: 9.8,
            heatindex_f: 49.6,
            dewpoint_c: 5.7,
            dewpoint_f: 42.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 2.0,
          },
          {
            time_epoch: 1679216400,
            time: '2023-03-19 12:00',
            temp_c: 10.0,
            temp_f: 50.0,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 8.1,
            wind_kph: 13.0,
            wind_degree: 11,
            wind_dir: 'NNE',
            pressure_mb: 1020.0,
            pressure_in: 30.11,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 79,
            cloud: 100,
            feelslike_c: 8.2,
            feelslike_f: 46.8,
            windchill_c: 8.2,
            windchill_f: 46.8,
            heatindex_c: 10.0,
            heatindex_f: 50.0,
            dewpoint_c: 6.5,
            dewpoint_f: 43.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 3.0,
          },
          {
            time_epoch: 1679220000,
            time: '2023-03-19 13:00',
            temp_c: 9.9,
            temp_f: 49.8,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 7,
            wind_dir: 'N',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 83,
            cloud: 100,
            feelslike_c: 7.8,
            feelslike_f: 46.0,
            windchill_c: 7.8,
            windchill_f: 46.0,
            heatindex_c: 9.9,
            heatindex_f: 49.8,
            dewpoint_c: 7.2,
            dewpoint_f: 45.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.7,
            gust_kph: 17.3,
            uv: 2.0,
          },
          {
            time_epoch: 1679223600,
            time: '2023-03-19 14:00',
            temp_c: 9.9,
            temp_f: 49.8,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 11,
            wind_dir: 'NNE',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 86,
            cloud: 100,
            feelslike_c: 7.8,
            feelslike_f: 46.0,
            windchill_c: 7.8,
            windchill_f: 46.0,
            heatindex_c: 9.9,
            heatindex_f: 49.8,
            dewpoint_c: 7.6,
            dewpoint_f: 45.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.2,
            gust_kph: 18.0,
            uv: 2.0,
          },
          {
            time_epoch: 1679227200,
            time: '2023-03-19 15:00',
            temp_c: 9.8,
            temp_f: 49.6,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 8.7,
            wind_kph: 14.0,
            wind_degree: 15,
            wind_dir: 'NNE',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 91,
            cloud: 100,
            feelslike_c: 7.8,
            feelslike_f: 46.0,
            windchill_c: 7.8,
            windchill_f: 46.0,
            heatindex_c: 9.8,
            heatindex_f: 49.6,
            dewpoint_c: 8.3,
            dewpoint_f: 46.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 2.0,
          },
          {
            time_epoch: 1679230800,
            time: '2023-03-19 16:00',
            temp_c: 9.7,
            temp_f: 49.5,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 17,
            wind_dir: 'NNE',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 93,
            cloud: 100,
            feelslike_c: 7.6,
            feelslike_f: 45.7,
            windchill_c: 7.6,
            windchill_f: 45.7,
            heatindex_c: 9.7,
            heatindex_f: 49.5,
            dewpoint_c: 8.6,
            dewpoint_f: 47.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.7,
            gust_kph: 17.3,
            uv: 2.0,
          },
          {
            time_epoch: 1679234400,
            time: '2023-03-19 17:00',
            temp_c: 9.8,
            temp_f: 49.6,
            is_day: 1,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 19,
            wind_dir: 'NNE',
            pressure_mb: 1020.0,
            pressure_in: 30.11,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 91,
            cloud: 100,
            feelslike_c: 7.7,
            feelslike_f: 45.9,
            windchill_c: 7.7,
            windchill_f: 45.9,
            heatindex_c: 9.8,
            heatindex_f: 49.6,
            dewpoint_c: 8.4,
            dewpoint_f: 47.1,
            will_it_rain: 1,
            chance_of_rain: 85,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.2,
            gust_kph: 18.0,
            uv: 2.0,
          },
          {
            time_epoch: 1679238000,
            time: '2023-03-19 18:00',
            temp_c: 9.7,
            temp_f: 49.5,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 22,
            wind_dir: 'NNE',
            pressure_mb: 1020.0,
            pressure_in: 30.12,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 90,
            cloud: 97,
            feelslike_c: 7.5,
            feelslike_f: 45.5,
            windchill_c: 7.5,
            windchill_f: 45.5,
            heatindex_c: 9.7,
            heatindex_f: 49.5,
            dewpoint_c: 8.1,
            dewpoint_f: 46.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.7,
            uv: 2.0,
          },
          {
            time_epoch: 1679241600,
            time: '2023-03-19 19:00',
            temp_c: 9.8,
            temp_f: 49.6,
            is_day: 1,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 24,
            wind_dir: 'NNE',
            pressure_mb: 1021.0,
            pressure_in: 30.14,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 89,
            cloud: 76,
            feelslike_c: 7.7,
            feelslike_f: 45.9,
            windchill_c: 7.7,
            windchill_f: 45.9,
            heatindex_c: 9.8,
            heatindex_f: 49.6,
            dewpoint_c: 8.1,
            dewpoint_f: 46.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.7,
            gust_kph: 17.3,
            uv: 2.0,
          },
          {
            time_epoch: 1679245200,
            time: '2023-03-19 20:00',
            temp_c: 9.1,
            temp_f: 48.4,
            is_day: 0,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 28,
            wind_dir: 'NNE',
            pressure_mb: 1021.0,
            pressure_in: 30.15,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 89,
            cloud: 68,
            feelslike_c: 7.0,
            feelslike_f: 44.6,
            windchill_c: 7.0,
            windchill_f: 44.6,
            heatindex_c: 9.1,
            heatindex_f: 48.4,
            dewpoint_c: 7.5,
            dewpoint_f: 45.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.7,
            gust_kph: 17.3,
            uv: 1.0,
          },
          {
            time_epoch: 1679248800,
            time: '2023-03-19 21:00',
            temp_c: 8.9,
            temp_f: 48.0,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 28,
            wind_dir: 'NNE',
            pressure_mb: 1021.0,
            pressure_in: 30.16,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 90,
            cloud: 51,
            feelslike_c: 7.0,
            feelslike_f: 44.6,
            windchill_c: 7.0,
            windchill_f: 44.6,
            heatindex_c: 8.9,
            heatindex_f: 48.0,
            dewpoint_c: 7.3,
            dewpoint_f: 45.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.6,
            gust_kph: 15.5,
            uv: 1.0,
          },
          {
            time_epoch: 1679252400,
            time: '2023-03-19 22:00',
            temp_c: 8.7,
            temp_f: 47.7,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 28,
            wind_dir: 'NNE',
            pressure_mb: 1021.0,
            pressure_in: 30.16,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 90,
            cloud: 48,
            feelslike_c: 6.9,
            feelslike_f: 44.4,
            windchill_c: 6.9,
            windchill_f: 44.4,
            heatindex_c: 8.7,
            heatindex_f: 47.7,
            dewpoint_c: 7.2,
            dewpoint_f: 45.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.7,
            gust_kph: 14.0,
            uv: 1.0,
          },
          {
            time_epoch: 1679256000,
            time: '2023-03-19 23:00',
            temp_c: 8.4,
            temp_f: 47.1,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 18,
            wind_dir: 'NNE',
            pressure_mb: 1021.0,
            pressure_in: 30.15,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 91,
            cloud: 59,
            feelslike_c: 6.8,
            feelslike_f: 44.2,
            windchill_c: 6.8,
            windchill_f: 44.2,
            heatindex_c: 8.4,
            heatindex_f: 47.1,
            dewpoint_c: 7.0,
            dewpoint_f: 44.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 1.0,
          },
        ],
      },
      {
        date: '2023-03-20',
        date_epoch: 1679270400,
        day: {
          maxtemp_c: 16.4,
          maxtemp_f: 61.5,
          mintemp_c: 7.2,
          mintemp_f: 45.0,
          avgtemp_c: 11.1,
          avgtemp_f: 52.0,
          maxwind_mph: 5.8,
          maxwind_kph: 9.4,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 71.0,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000,
          },
          uv: 4.0,
        },
        astro: {
          sunrise: '07:08 AM',
          sunset: '07:16 PM',
          moonrise: '06:44 AM',
          moonset: '05:47 PM',
          moon_phase: 'Waning Crescent',
          moon_illumination: '4',
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1679259600,
            time: '2023-03-20 00:00',
            temp_c: 8.0,
            temp_f: 46.4,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 30,
            wind_dir: 'NNE',
            pressure_mb: 1021.0,
            pressure_in: 30.15,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 91,
            cloud: 55,
            feelslike_c: 6.4,
            feelslike_f: 43.5,
            windchill_c: 6.4,
            windchill_f: 43.5,
            heatindex_c: 8.0,
            heatindex_f: 46.4,
            dewpoint_c: 6.6,
            dewpoint_f: 43.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.1,
            gust_kph: 13.0,
            uv: 1.0,
          },
          {
            time_epoch: 1679263200,
            time: '2023-03-20 01:00',
            temp_c: 7.9,
            temp_f: 46.2,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 35,
            wind_dir: 'NE',
            pressure_mb: 1021.0,
            pressure_in: 30.15,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 90,
            cloud: 50,
            feelslike_c: 6.3,
            feelslike_f: 43.3,
            windchill_c: 6.3,
            windchill_f: 43.3,
            heatindex_c: 7.9,
            heatindex_f: 46.2,
            dewpoint_c: 6.4,
            dewpoint_f: 43.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 1.0,
          },
          {
            time_epoch: 1679266800,
            time: '2023-03-20 02:00',
            temp_c: 7.8,
            temp_f: 46.0,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 27,
            wind_dir: 'NNE',
            pressure_mb: 1021.0,
            pressure_in: 30.14,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 89,
            cloud: 42,
            feelslike_c: 6.5,
            feelslike_f: 43.7,
            windchill_c: 6.5,
            windchill_f: 43.7,
            heatindex_c: 7.8,
            heatindex_f: 46.0,
            dewpoint_c: 6.2,
            dewpoint_f: 43.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.5,
            gust_kph: 10.4,
            uv: 1.0,
          },
          {
            time_epoch: 1679270400,
            time: '2023-03-20 03:00',
            temp_c: 7.6,
            temp_f: 45.7,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 31,
            wind_dir: 'NNE',
            pressure_mb: 1021.0,
            pressure_in: 30.14,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 90,
            cloud: 41,
            feelslike_c: 6.7,
            feelslike_f: 44.1,
            windchill_c: 6.7,
            windchill_f: 44.1,
            heatindex_c: 7.6,
            heatindex_f: 45.7,
            dewpoint_c: 6.1,
            dewpoint_f: 43.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 1.0,
          },
          {
            time_epoch: 1679274000,
            time: '2023-03-20 04:00',
            temp_c: 7.4,
            temp_f: 45.3,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 30,
            wind_dir: 'NNE',
            pressure_mb: 1021.0,
            pressure_in: 30.15,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 91,
            cloud: 41,
            feelslike_c: 6.8,
            feelslike_f: 44.2,
            windchill_c: 6.8,
            windchill_f: 44.2,
            heatindex_c: 7.4,
            heatindex_f: 45.3,
            dewpoint_c: 6.0,
            dewpoint_f: 42.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.5,
            gust_kph: 7.2,
            uv: 1.0,
          },
          {
            time_epoch: 1679277600,
            time: '2023-03-20 05:00',
            temp_c: 7.3,
            temp_f: 45.1,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 39,
            wind_dir: 'NE',
            pressure_mb: 1021.0,
            pressure_in: 30.15,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 91,
            cloud: 41,
            feelslike_c: 6.6,
            feelslike_f: 43.9,
            windchill_c: 6.6,
            windchill_f: 43.9,
            heatindex_c: 7.3,
            heatindex_f: 45.1,
            dewpoint_c: 5.9,
            dewpoint_f: 42.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 1.0,
          },
          {
            time_epoch: 1679281200,
            time: '2023-03-20 06:00',
            temp_c: 7.2,
            temp_f: 45.0,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 49,
            wind_dir: 'NE',
            pressure_mb: 1021.0,
            pressure_in: 30.14,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 90,
            cloud: 34,
            feelslike_c: 6.4,
            feelslike_f: 43.5,
            windchill_c: 6.4,
            windchill_f: 43.5,
            heatindex_c: 7.2,
            heatindex_f: 45.0,
            dewpoint_c: 5.7,
            dewpoint_f: 42.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 1.0,
          },
          {
            time_epoch: 1679284800,
            time: '2023-03-20 07:00',
            temp_c: 7.4,
            temp_f: 45.3,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 57,
            wind_dir: 'ENE',
            pressure_mb: 1021.0,
            pressure_in: 30.14,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 88,
            cloud: 25,
            feelslike_c: 6.9,
            feelslike_f: 44.4,
            windchill_c: 6.9,
            windchill_f: 44.4,
            heatindex_c: 7.4,
            heatindex_f: 45.3,
            dewpoint_c: 5.6,
            dewpoint_f: 42.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.0,
            gust_kph: 6.5,
            uv: 1.0,
          },
          {
            time_epoch: 1679288400,
            time: '2023-03-20 08:00',
            temp_c: 8.3,
            temp_f: 46.9,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 55,
            wind_dir: 'NE',
            pressure_mb: 1021.0,
            pressure_in: 30.14,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 82,
            cloud: 11,
            feelslike_c: 8.4,
            feelslike_f: 47.1,
            windchill_c: 8.4,
            windchill_f: 47.1,
            heatindex_c: 8.3,
            heatindex_f: 46.9,
            dewpoint_c: 5.4,
            dewpoint_f: 41.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.9,
            gust_kph: 4.7,
            uv: 3.0,
          },
          {
            time_epoch: 1679292000,
            time: '2023-03-20 09:00',
            temp_c: 9.5,
            temp_f: 49.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 48,
            wind_dir: 'NE',
            pressure_mb: 1021.0,
            pressure_in: 30.15,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 73,
            cloud: 2,
            feelslike_c: 9.4,
            feelslike_f: 48.9,
            windchill_c: 9.4,
            windchill_f: 48.9,
            heatindex_c: 9.5,
            heatindex_f: 49.1,
            dewpoint_c: 5.0,
            dewpoint_f: 41.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.1,
            gust_kph: 5.0,
            uv: 3.0,
          },
          {
            time_epoch: 1679295600,
            time: '2023-03-20 10:00',
            temp_c: 10.9,
            temp_f: 51.6,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 47,
            wind_dir: 'NE',
            pressure_mb: 1021.0,
            pressure_in: 30.15,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 65,
            cloud: 7,
            feelslike_c: 10.9,
            feelslike_f: 51.6,
            windchill_c: 10.9,
            windchill_f: 51.6,
            heatindex_c: 10.9,
            heatindex_f: 51.6,
            dewpoint_c: 4.6,
            dewpoint_f: 40.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 4.0,
          },
          {
            time_epoch: 1679299200,
            time: '2023-03-20 11:00',
            temp_c: 13.3,
            temp_f: 55.9,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 70,
            wind_dir: 'ENE',
            pressure_mb: 1021.0,
            pressure_in: 30.14,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 59,
            cloud: 10,
            feelslike_c: 13.7,
            feelslike_f: 56.7,
            windchill_c: 13.7,
            windchill_f: 56.7,
            heatindex_c: 13.3,
            heatindex_f: 55.9,
            dewpoint_c: 5.6,
            dewpoint_f: 42.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.1,
            gust_kph: 5.0,
            uv: 4.0,
          },
          {
            time_epoch: 1679302800,
            time: '2023-03-20 12:00',
            temp_c: 13.8,
            temp_f: 56.8,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 96,
            wind_dir: 'E',
            pressure_mb: 1020.0,
            pressure_in: 30.11,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 57,
            cloud: 21,
            feelslike_c: 14.5,
            feelslike_f: 58.1,
            windchill_c: 14.5,
            windchill_f: 58.1,
            heatindex_c: 13.8,
            heatindex_f: 56.8,
            dewpoint_c: 5.5,
            dewpoint_f: 41.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.5,
            gust_kph: 4.0,
            uv: 4.0,
          },
          {
            time_epoch: 1679306400,
            time: '2023-03-20 13:00',
            temp_c: 14.5,
            temp_f: 58.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 104,
            wind_dir: 'ESE',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 57,
            cloud: 14,
            feelslike_c: 14.5,
            feelslike_f: 58.1,
            windchill_c: 14.5,
            windchill_f: 58.1,
            heatindex_c: 14.5,
            heatindex_f: 58.1,
            dewpoint_c: 6.1,
            dewpoint_f: 43.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.0,
            gust_kph: 3.2,
            uv: 4.0,
          },
          {
            time_epoch: 1679310000,
            time: '2023-03-20 14:00',
            temp_c: 16.2,
            temp_f: 61.2,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 2.0,
            wind_kph: 3.2,
            wind_degree: 77,
            wind_dir: 'ENE',
            pressure_mb: 1019.0,
            pressure_in: 30.08,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 55,
            cloud: 0,
            feelslike_c: 16.2,
            feelslike_f: 61.2,
            windchill_c: 16.2,
            windchill_f: 61.2,
            heatindex_c: 16.2,
            heatindex_f: 61.2,
            dewpoint_c: 7.2,
            dewpoint_f: 45.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.2,
            gust_kph: 3.6,
            uv: 5.0,
          },
          {
            time_epoch: 1679313600,
            time: '2023-03-20 15:00',
            temp_c: 16.4,
            temp_f: 61.5,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 74,
            wind_dir: 'ENE',
            pressure_mb: 1018.0,
            pressure_in: 30.06,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 54,
            cloud: 0,
            feelslike_c: 16.4,
            feelslike_f: 61.5,
            windchill_c: 16.4,
            windchill_f: 61.5,
            heatindex_c: 16.4,
            heatindex_f: 61.5,
            dewpoint_c: 7.2,
            dewpoint_f: 45.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.8,
            gust_kph: 6.1,
            uv: 5.0,
          },
          {
            time_epoch: 1679317200,
            time: '2023-03-20 16:00',
            temp_c: 16.4,
            temp_f: 61.5,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 75,
            wind_dir: 'ENE',
            pressure_mb: 1018.0,
            pressure_in: 30.05,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 54,
            cloud: 0,
            feelslike_c: 16.4,
            feelslike_f: 61.5,
            windchill_c: 16.4,
            windchill_f: 61.5,
            heatindex_c: 16.4,
            heatindex_f: 61.5,
            dewpoint_c: 7.2,
            dewpoint_f: 45.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.8,
            gust_kph: 6.1,
            uv: 5.0,
          },
          {
            time_epoch: 1679320800,
            time: '2023-03-20 17:00',
            temp_c: 16.0,
            temp_f: 60.8,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 54,
            wind_dir: 'NE',
            pressure_mb: 1018.0,
            pressure_in: 30.05,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 56,
            cloud: 0,
            feelslike_c: 16.0,
            feelslike_f: 60.8,
            windchill_c: 16.0,
            windchill_f: 60.8,
            heatindex_c: 16.0,
            heatindex_f: 60.8,
            dewpoint_c: 7.3,
            dewpoint_f: 45.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 5.0,
          },
          {
            time_epoch: 1679324400,
            time: '2023-03-20 18:00',
            temp_c: 15.0,
            temp_f: 59.0,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 62,
            wind_dir: 'ENE',
            pressure_mb: 1018.0,
            pressure_in: 30.05,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 60,
            cloud: 0,
            feelslike_c: 15.0,
            feelslike_f: 59.0,
            windchill_c: 15.0,
            windchill_f: 59.0,
            heatindex_c: 15.0,
            heatindex_f: 59.0,
            dewpoint_c: 7.2,
            dewpoint_f: 45.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 5.0,
          },
          {
            time_epoch: 1679328000,
            time: '2023-03-20 19:00',
            temp_c: 14.1,
            temp_f: 57.4,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 68,
            wind_dir: 'ENE',
            pressure_mb: 1018.0,
            pressure_in: 30.05,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 0,
            feelslike_c: 14.0,
            feelslike_f: 57.2,
            windchill_c: 14.0,
            windchill_f: 57.2,
            heatindex_c: 14.1,
            heatindex_f: 57.4,
            dewpoint_c: 6.6,
            dewpoint_f: 43.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 4.0,
          },
          {
            time_epoch: 1679331600,
            time: '2023-03-20 20:00',
            temp_c: 10.9,
            temp_f: 51.6,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 69,
            wind_dir: 'ENE',
            pressure_mb: 1018.0,
            pressure_in: 30.05,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 0,
            feelslike_c: 10.4,
            feelslike_f: 50.7,
            windchill_c: 10.4,
            windchill_f: 50.7,
            heatindex_c: 10.9,
            heatindex_f: 51.6,
            dewpoint_c: 3.7,
            dewpoint_f: 38.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.5,
            gust_kph: 10.4,
            uv: 1.0,
          },
          {
            time_epoch: 1679335200,
            time: '2023-03-20 21:00',
            temp_c: 10.5,
            temp_f: 50.9,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 73,
            wind_dir: 'ENE',
            pressure_mb: 1017.0,
            pressure_in: 30.04,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 62,
            cloud: 0,
            feelslike_c: 9.9,
            feelslike_f: 49.8,
            windchill_c: 9.9,
            windchill_f: 49.8,
            heatindex_c: 10.5,
            heatindex_f: 50.9,
            dewpoint_c: 3.5,
            dewpoint_f: 38.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 1.0,
          },
          {
            time_epoch: 1679338800,
            time: '2023-03-20 22:00',
            temp_c: 10.2,
            temp_f: 50.4,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 74,
            wind_dir: 'ENE',
            pressure_mb: 1017.0,
            pressure_in: 30.03,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 62,
            cloud: 0,
            feelslike_c: 9.8,
            feelslike_f: 49.6,
            windchill_c: 9.8,
            windchill_f: 49.6,
            heatindex_c: 10.2,
            heatindex_f: 50.4,
            dewpoint_c: 3.3,
            dewpoint_f: 37.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.0,
            gust_kph: 9.7,
            uv: 1.0,
          },
          {
            time_epoch: 1679342400,
            time: '2023-03-20 23:00',
            temp_c: 10.1,
            temp_f: 50.2,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 76,
            wind_dir: 'ENE',
            pressure_mb: 1017.0,
            pressure_in: 30.02,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 62,
            cloud: 4,
            feelslike_c: 9.9,
            feelslike_f: 49.8,
            windchill_c: 9.9,
            windchill_f: 49.8,
            heatindex_c: 10.1,
            heatindex_f: 50.2,
            dewpoint_c: 3.2,
            dewpoint_f: 37.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 1.0,
          },
        ],
      },
    ],
  },
}
